-- MySQL Script generated by MySQL Workbench
-- 05/30/22 14:28:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projectmusic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectmusic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectmusic` DEFAULT CHARACTER SET utf8 ;
USE `projectmusic` ;

-- -----------------------------------------------------
-- Table `projectmusic`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`album` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`album` (
  `id_al` INT NOT NULL AUTO_INCREMENT,
  `nome_al` VARCHAR(200) NOT NULL,
  `ano_al` INT NOT NULL,
  PRIMARY KEY (`id_al`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmusic`.`musica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`musica` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`musica` (
  `id_m` INT NOT NULL AUTO_INCREMENT,
  `titulo_m` VARCHAR(200) NOT NULL,
  `album_id_al` INT NOT NULL,
  PRIMARY KEY (`id_m`),
  INDEX `fk_musica_album1_idx` (`album_id_al` ASC),
  CONSTRAINT `fk_musica_album1`
    FOREIGN KEY (`album_id_al`)
    REFERENCES `projectmusic`.`album` (`id_al`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmusic`.`artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`artista` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`artista` (
  `id_a` INT NOT NULL AUTO_INCREMENT,
  `nome_a` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_a`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmusic`.`musica_has_artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`musica_has_artista` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`musica_has_artista` (
  `musica_id_m` INT NOT NULL,
  `artista_id_a` INT NOT NULL,
  PRIMARY KEY (`musica_id_m`, `artista_id_a`),
  INDEX `fk_musica_has_artista_artista1_idx` (`artista_id_a` ASC),
  INDEX `fk_musica_has_artista_musica1_idx` (`musica_id_m` ASC),
  CONSTRAINT `fk_musica_has_artista_musica1`
    FOREIGN KEY (`musica_id_m`)
    REFERENCES `projectmusic`.`musica` (`id_m`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musica_has_artista_artista1`
    FOREIGN KEY (`artista_id_a`)
    REFERENCES `projectmusic`.`artista` (`id_a`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmusic`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`users` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`users` (
  `id_u` INT NOT NULL AUTO_INCREMENT,
  `nome_u` VARCHAR(45) NOT NULL,
  `pass_u` VARCHAR(999) NOT NULL,
  `nivel_u` INT NOT NULL,
  PRIMARY KEY (`id_u`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmusic`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`generos` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`generos` (
  `id_g` INT NOT NULL AUTO_INCREMENT,
  `nome_g` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_g`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmusic`.`musica_has_generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`musica_has_generos` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`musica_has_generos` (
  `musica_id_m` INT NOT NULL,
  `generos_id_g` INT NOT NULL,
  PRIMARY KEY (`musica_id_m`, `generos_id_g`),
  INDEX `fk_musica_has_generos_generos1_idx` (`generos_id_g` ASC),
  INDEX `fk_musica_has_generos_musica1_idx` (`musica_id_m` ASC),
  CONSTRAINT `fk_musica_has_generos_musica1`
    FOREIGN KEY (`musica_id_m`)
    REFERENCES `projectmusic`.`musica` (`id_m`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musica_has_generos_generos1`
    FOREIGN KEY (`generos_id_g`)
    REFERENCES `projectmusic`.`generos` (`id_g`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmusic`.`album_has_generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmusic`.`album_has_generos` ;

CREATE TABLE IF NOT EXISTS `projectmusic`.`album_has_generos` (
  `album_id_al` INT NOT NULL,
  `generos_id_g` INT NOT NULL,
  PRIMARY KEY (`album_id_al`, `generos_id_g`),
  INDEX `fk_album_has_generos_generos1_idx` (`generos_id_g` ASC),
  INDEX `fk_album_has_generos_album1_idx` (`album_id_al` ASC),
  CONSTRAINT `fk_album_has_generos_album1`
    FOREIGN KEY (`album_id_al`)
    REFERENCES `projectmusic`.`album` (`id_al`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_has_generos_generos1`
    FOREIGN KEY (`generos_id_g`)
    REFERENCES `projectmusic`.`generos` (`id_g`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
